### ISSUE TITLE
Failed to install through chromewebstore due to being deleted.

### ISSUE THREAD

**Issue by NoapMat** [c3cbot/c3c-fbstate#20]
Can't seem to install it there.
[HERE](https://chromewebstore.google.com/detail/c3c-fbstate-utility/ekgmbjnloldgikngiachemodebfpkgdp)
![scr](https://github.com/user-attachments/assets/2703be8b-3010-4e66-b2ee-8fcf540228c4)

**Comment by BadAimWeeb** [comment]
Known issue actually due to someone stealing and send a malicious DMCA request to Google.
We'll have to wait for Google to reinstate the extension on the Chrome Web Store.

![image](https://github.com/user-attachments/assets/a79b3df2-ecab-4d4c-b5d4-af135bac94e9)

_funny thing is google responded on August 20 and today is September 6, well past the 10 days they told in the response :)_

**Comment by NoapMat** [comment]
> Known issue actually due to someone stealing and send a malicious DMCA request to Google. We'll have to wait for Google to reinstate the extension on the Chrome Web Store.
> 
> ![image](https://private-user-images.githubusercontent.com/29724654/365042229-a79b3df2-ecab-4d4c-b5d4-af135bac94e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU2MDE1MTEsIm5iZiI6MTcyNTYwMTIxMSwicGF0aCI6Ii8yOTcyNDY1NC8zNjUwNDIyMjktYTc5YjNkZjItZWNhYi00ZDRjLWI1ZDQtYWYxMzViYWM5NGU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA2VDA1NDAxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhZmNkMmQ2YWNkMjMwYjI2MTRjYTA0MDM1YjBjZmQyNmY4YjMzNjRmZDgyMDk1NWFkMjA4OGM3MGQwYjlkODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CL5MotzZh9GBaauBNQ2lPt2I-BUMBtP-aJ2Z3ELRW00)
> 
> _funny thing is google responded on August 20 and today is September 9, well past the 10 days they told in the response :)_

Thats nuts lmfao.

**Comment by BadAimWeeb** [comment]
You can also install *c3c-fbstate* by just drag-and-drop [the .crx file from release](https://github.com/c3cbot/c3c-fbstate/releases/download/2.0.0/ekgmbjnloldgikngiachemodebfpkgdp.crx) to `chrome://extension` as a temporary measure. It is the identical version if you downloaded from Chrome Web Store (same ID and signed by Google), and you'll still get auto-update if DMCA is cleared afaik :)

**Comment by NoapMat** [comment]
> You can also install _c3c-fbstate_ by just drag-and-drop [the .crx file from release](https://github.com/c3cbot/c3c-fbstate/releases/download/2.0.0/ekgmbjnloldgikngiachemodebfpkgdp.crx) to `chrome://extension` as a temporary measure. It is the identical version if you downloaded from Chrome Web Store (same ID and signed by Google), and you'll still get auto-update if DMCA is cleared afaik :)

Okay, thanks man.

**Comment by NoapMat** [comment]
Can i add this question a 'lil bit?
Is this possible on CLI? Or a cli usage that would easily spew out new session/appstate and logout the session?

**Comment by BadAimWeeb** [comment]
> Can i add this question a 'lil bit?
> Is this possible on CLI? Or a cli usage that would easily spew out new session/appstate and logout the session?

Unfortunately no, CLI usage is not available. Also if CLI exists it would not be on this repo as it's out of scope.

Great idea though, I might consider making a separate CLI on a separate repo for automation.

**Comment by NoapMat** [comment]
> > Can i add this question a 'lil bit?
> > Is this possible on CLI? Or a cli usage that would easily spew out new session/appstate and logout the session?
> 
> Unfortunately no, CLI usage is not available. Also if CLI exists it would not be on this repo as it's out of scope.
> 
> Great idea though, I might consider making a separate CLI on a separate repo for automation.

Woah! damnnn!!! Thanks man.

**Comment by BadAimWeeb** [comment]
Good news: DMCA on the extension has been removed, but we'll have to wait for a day or two for the new names (see #21). You'll receive the new version with the new name soon (as it's still the same ID).

**Comment by BadAimWeeb** [comment]
Close issue as all current stores have been updated with the new name and is available for install.
